version: '3'
services:
  app:
    image: tianlechen/hf-inference
    ports:
      - 8000:8000
    # # uncomment the following for gpu
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         capabilities: [gpu]
