version: '3'
services:
  app:
    image: tianlechen/hf-inference
    ports:
      - 8000:8000
    deploy:
      restart_policy:
        condition: on-failure
      # # uncomment the following for gpu
      # resources:
      #   reservations:
      #     devices:
      #     - driver: nvidia
      #       capabilities: [gpu]
